-- CREATE TABLE `jogadores` (
--         `id` INT(10) AUTO_INCREMENT PRIMARY KEY,
--         `nomeJogador` longtext NOT NULL
-- ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- INSERT INTO jogadores (jogador) VALUES
--                                         ('Jogador 1'),
--                                         ('Jogador 2'),
--                                         ('Jogador 3'),
--                                         ('Jogador 4');